### ISSUE TITLE
test the MSP430 backend

### ISSUE THREAD

**Issue by japaric** [japaric/svd2rust#125]
#120 added support for the MSP430 architecture but didn't add any test. We should add a few MSP430 SVD files to our test suite. The problem is where do we get them. There's no database like the Cortex-M one.

@pftbest @cr1901 @awygle You all have have MSP430 micros -- I hope you all have different ones. Any plans for making a SVD file database of MSP430 devices?

**Comment by jamesmunns** [comment]
@japaric we have at least one svd in CI, is this okay to close, or would you prefer more coverage?

**Comment by japaric** [comment]
One target is fine. If someone finds some problem with code generation for MSP430 we can always add more SVD files as regression tests.
