### ISSUE TITLE
SVD Registers with no dimIndex

### ISSUE THREAD

**Issue by lucasbrendel** [japaric/svd2rust#150]
According to the CMSIS standard:
https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_special.html 

dimElementGroups with "[%s]" in their name are not suppose to use the dimIndex tag. I have an SVD that currently is doing this but getting an error due to the tag missing. The SVD file is loaded in #146 but will only get that far if my PR in japaric/svd#40 is used.

Requesting the the dimIndex missing be allowed if name contains [%s]

**Comment by therealprof** [comment]
The Atmel SAM SVD files also have that exact same problem.

**Comment by lucasbrendel** [comment]
I am working on a fix for it. I have something that will get passed the issue and generate the .rs file but I am still testing to make sure it actually does what it needs to
