### ISSUE TITLE
[CI] `VENDOR=Freescale` build is timing out

### ISSUE THREAD

**Issue by japaric** [japaric/svd2rust#166]
This is probably caused by the recent changes in Cargo defaults: Cargo now uses incremental compilation by default in dev builds. Because we are reusing the same Cargo project to dump the code generated from different SVD files the incremental compilation must be doing a lot of useless work diffing the new version of the crate source vs the old one, which was generated from a totally different SVD file.

Disabling incremental compilation should fix the timeout.

**Comment by jamesmunns** [comment]
@japaric is this okay to close? I believe it has been addressed already.

**Comment by japaric** [comment]
Yes, I disabled incremental compilation and that seemed to fix it.
