### ISSUE TITLE
Use `volatile-register` instead of `vcell`?

### ISSUE THREAD

**Issue by whitequark** [japaric/svd2rust#171]
It seems odd that cortex-m uses one crate and svd2rust another.

**Comment by docbrown** [comment]
AFAICT, `volatile-register` wraps `vcell` with an API that's more convenient for manually implementing peripherals like in the `cortex-m` crate. Since `svd2rust` is generating code automatically, it doesn't need that extra level of abstraction so it just uses `vcell` directly.

**Comment by jamesmunns** [comment]
@whitequark is this okay to close for you?
