### ISSUE TITLE
Where to find SVD files?

### ISSUE THREAD

**Issue by zmitchell** [japaric/svd2rust#228]
Sorry if this is the wrong place to ask this, but I’m basically brand new to embedded (haven’t started, really). I’m wondering if there is a standard place that I haven’t been able to find that has SVD files for various devices.

I may be interested in making a driver for the Bosch BME280 temp/pressure/humidity sensor, but I haven’t been able to find a SVD file for it.

Looking around I did find [this resource](http://www.keil.com/dd2/Pack/), but it doesn’t have anything from Bosch. Thinking that this may be something that the manufacturer supplies on their website, I looked around the Bosch website without any luck.

Am I missing something? Where should I be looking?

**Comment by jamesmunns** [comment]
Closing this as the question has been answered.
