### ISSUE TITLE
Use volatile_register::RW::modify<F>(&mut self, func: F) where F: FnOnce(T) -> T

### ISSUE THREAD

**Issue by thejpster** [japaric/svd2rust#24]
volatile_register now has a modify() method, and I think the output of svd2rust would be shorter if it used that rather than writing out its own modify methods.

**Comment by japaric** [comment]
:1: from me if the output is shorter.

**Comment by japaric** [comment]
No longer applies as mutation is allowed through a `&-` reference (Cell-style mutation) and the volatile-cell dependency has been dropped.
