### ISSUE TITLE
Function name collision avoidance

### ISSUE THREAD

**Issue by astro** [japaric/svd2rust#42]
The .svd file I use has multiple **reserved** bit ranges per register, leading to duplicate `fn reserved()` in struct impls. If that happens, those fields could either be omitted or get mangled into `reserved1`, `reserved2`, ...

**Comment by japaric** [comment]
Can you provide an example svd? I suppose those bit ranges are not supposed to be exposed at all.

**Comment by astro** [comment]
https://www.lpcware.com/system/files/LPC43xx_43Sxx._svd_v10.zip
